; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non-commercial use only

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{B4FAEEE4-E004-4647-B3BE-479DF43F1025}
AppName=Pixel Guard
AppVersion=1.5
;AppVerName=Pixel Guard 1.5
AppPublisher=UraniumX
AppPublisherURL=https://github.com/UraniummX/Steganography
AppSupportURL=https://github.com/UraniummX/Steganography
AppUpdatesURL=https://github.com/UraniummX/Steganography
DefaultDirName={autopf}\Pixel Guard 
UninstallDisplayIcon={app}\PixelGuard.exe
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
DisableProgramGroupPage=yes
; Uncomment the following line to run in non administrative install mode (install for current user only).
;PrivilegesRequired=lowest
OutputBaseFilename=PixelGuardSetup
SetupIconFile=C:\Users\Urani\Documents\Programming Fundementals\Project_Soecial\favicon.ico
SolidCompression=yes
WizardStyle=modern dynamic windows11

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "C:\Users\Urani\Documents\Programming Fundementals\Project_Soecial\dist\PixelGuard.exe"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\Pixel Guard"; Filename: "{app}\PixelGuard.exe"
Name: "{autodesktop}\Pixel Guard"; Filename: "{app}\PixelGuard.exe"; Tasks: desktopicon

[Run]
Filename: "{app}\PixelGuard.exe"; Description: "{cm:LaunchProgram,Pixel Guard}"; Flags: nowait postinstall skipifsilent

